services:
  - type: web
    name: hangar5
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./data/hangar5.db
      - key: NEXT_PUBLIC_URL
        value: https://hangar5.onrender.com
      - key: HOSTNAME
        value: 0.0.0.0
