import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "@prisma/client";
import crypto from "crypto";

const dbUrl = process.env.DATABASE_URL || "file:/data/hangar5.db";
const adapter = new PrismaBetterSqlite3({ url: dbUrl });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 [seed-demo] Starting...");

  // ── Idempotency: skip if demo data already exists ──────────────────────────
  const customerCount = await prisma.customer.count();
  if (customerCount > 0) {
    console.log("⚠️  [seed-demo] Demo data already exists, skipping.");
    await prisma.$disconnect();
    return;
  }

  // ── Require menu items (generated by seed-restaurant-all) ─────────────────
  const menuItems = await prisma.menuItem.findMany({ take: 12 });
  if (menuItems.length < 7) {
    console.log("⚠️  [seed-demo] Not enough menu items found, skipping (run seed-restaurant-all first).");
    await prisma.$disconnect();
    return;
  }

  console.log("📦 [seed-demo] Seeding demo operational data...");

  await prisma.$transaction(async (tx) => {
    // ═══ 1. Customers ═══════════════════════════════════════════════
    const c1 = await tx.customer.create({ data: { name: "Ana Martínez", phone: "722 123 4567", email: "ana@demo.com", hasCredit: true, notes: "Cliente frecuente" } });
    const c2 = await tx.customer.create({ data: { name: "Luis Hernández", phone: "722 234 5678", hasCredit: true } });
    const c3 = await tx.customer.create({ data: { name: "María López", phone: "722 345 6789" } });
    const c4 = await tx.customer.create({ data: { name: "Carlos Gómez", email: "carlos@demo.com" } });
    console.log("  ✅ 4 clientes");

    // ═══ 2. Staff ════════════════════════════════════════════════════
    const s1 = await tx.staff.create({ data: { name: "Pedro Mesero", role: "MESERO", pin: "1111", hourlyRate: 3500 } });
    const s2 = await tx.staff.create({ data: { name: "Sofía Mesera", role: "MESERO", pin: "2222", hourlyRate: 3500 } });
    const s3 = await tx.staff.create({ data: { name: "Juan Mesero", role: "MESERO", pin: "3333", hourlyRate: 3500 } });
    const gerente = await tx.staff.create({ data: { name: "Rosa Gerente", role: "GERENTE", pin: "9999", hourlyRate: 6000 } });
    console.log("  ✅ 4 staff (3 meseros + 1 gerente)");

    // ═══ 3. Tables ═══════════════════════════════════════════════════
    const t1 = await tx.table.create({ data: { number: "1", qrToken: crypto.randomUUID(), capacity: 4, location: "Terraza" } });
    const t2 = await tx.table.create({ data: { number: "2", qrToken: crypto.randomUUID(), capacity: 4, location: "Interior" } });
    const t3 = await tx.table.create({ data: { number: "3", qrToken: crypto.randomUUID(), capacity: 6, location: "Jardín" } });
    console.log("  ✅ 3 mesas");

    // ═══ 4. Service sessions ════════════════════════════════════════
    const sess1 = await tx.serviceSession.create({ data: { type: "TABLE", label: "Mesa 1", tableId: t1.id, customerId: c1.id, status: "OPEN" } });
    const sess2 = await tx.serviceSession.create({ data: { type: "TABLE", label: "Mesa 2", tableId: t2.id, customerId: c2.id, status: "OPEN" } });
    const sess3 = await tx.serviceSession.create({ data: { type: "TAB", label: "Grupo Carlos", customerId: c4.id, status: "OPEN" } });
    console.log("  ✅ 3 sesiones");

    // ═══ 5. Orders in various states ════════════════════════════════
    const mkOrder = (data: any) => tx.order.create({ data });

    // Order 1 — PAID (completada)
    const o1 = await mkOrder({ serviceSessionId: sess1.id, source: "WAITER", status: "PAID", subtotal: 12000, tax: 1920, total: 13920, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3) });
    // Order 2 — SERVED
    const o2 = await mkOrder({ serviceSessionId: sess2.id, source: "WAITER", status: "SERVED", subtotal: 8000, tax: 1280, total: 9280, createdAt: new Date(Date.now() - 1000 * 60 * 40) });
    // Order 3 — READY
    const o3 = await mkOrder({ serviceSessionId: sess1.id, source: "QR", status: "READY", subtotal: 6000, tax: 960, total: 6960, createdAt: new Date(Date.now() - 1000 * 60 * 25) });
    // Order 4 — IN_KITCHEN
    const o4 = await mkOrder({ serviceSessionId: sess3.id, source: "WAITER", status: "IN_KITCHEN", subtotal: 9500, tax: 1520, total: 11020, createdAt: new Date(Date.now() - 1000 * 60 * 15) });
    // Order 5 — PLACED
    const o5 = await mkOrder({ serviceSessionId: sess2.id, source: "QR", status: "PLACED", subtotal: 4500, tax: 720, total: 5220, createdAt: new Date(Date.now() - 1000 * 60 * 8) });
    // Order 6 — CANCELLED (con actor + reason)
    const o6 = await mkOrder({ serviceSessionId: sess3.id, source: "ADMIN", status: "CANCELLED", subtotal: 3000, tax: 480, total: 3480, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2) });
    console.log("  ✅ 6 órdenes en distintos estados");

    // ═══ 6. Order items ═════════════════════════════════════════════
    const mkItem = (orderId: string, menuItemId: string, qty: number, price: number, status: string) =>
      tx.orderItem.create({ data: { orderId, menuItemId, quantity: qty, unitPrice: price, status } });

    await mkItem(o1.id, menuItems[0].id, 2, menuItems[0].basePrice, "SERVED");
    await mkItem(o1.id, menuItems[1].id, 1, menuItems[1].basePrice, "SERVED");
    await mkItem(o2.id, menuItems[2].id, 1, menuItems[2].basePrice, "SERVED");
    await mkItem(o3.id, menuItems[3].id, 1, menuItems[3].basePrice, "READY");
    await mkItem(o4.id, menuItems[4].id, 2, menuItems[4].basePrice, "IN_PREP");
    await mkItem(o5.id, menuItems[5].id, 1, menuItems[5].basePrice, "PENDING");
    await mkItem(o6.id, menuItems[6].id, 1, menuItems[6].basePrice, "CANCELLED");
    console.log("  ✅ Items de orden");

    // ═══ 7. Status events (for orders audit) ════════════════════════
    await tx.orderStatusEvent.createMany({
      data: [
        { orderId: o1.id, fromStatus: "PLACED", toStatus: "IN_KITCHEN" },
        { orderId: o1.id, fromStatus: "IN_KITCHEN", toStatus: "READY" },
        { orderId: o1.id, fromStatus: "READY", toStatus: "SERVED" },
        { orderId: o1.id, fromStatus: "SERVED", toStatus: "PAID" },
        { orderId: o2.id, fromStatus: "PLACED", toStatus: "IN_KITCHEN" },
        { orderId: o2.id, fromStatus: "IN_KITCHEN", toStatus: "READY" },
        { orderId: o2.id, fromStatus: "READY", toStatus: "SERVED" },
        { orderId: o3.id, fromStatus: "PLACED", toStatus: "IN_KITCHEN" },
        { orderId: o3.id, fromStatus: "IN_KITCHEN", toStatus: "READY" },
        { orderId: o6.id, fromStatus: "PLACED", toStatus: "CANCELLED", actorName: "Supervisor", reason: "Error al tomar la orden" },
      ],
    });
    console.log("  ✅ Eventos de estado");

    // ═══ 8. Payments ════════════════════════════════════════════════
    await tx.payment.create({ data: { orderId: o1.id, amount: o1.total, method: "CARD", status: "COMPLETED", paidAt: new Date() } });
    await tx.payment.create({ data: { orderId: o2.id, amount: o2.total, method: "CASH", status: "COMPLETED", paidAt: new Date() } });
    console.log("  ✅ Pagos");

    // ═══ 9. Ledger entries (account charges) ════════════════════════
    await tx.customerLedgerEntry.create({ data: { customerId: c1.id, amount: 13920, type: "CHARGE", serviceSessionId: sess1.id, note: "Orden #" + o1.id.slice(-6) } });
    await tx.customerLedgerEntry.create({ data: { customerId: c2.id, amount: 9280, type: "CHARGE", serviceSessionId: sess2.id, note: "Orden #" + o2.id.slice(-6) } });
    console.log("  ✅ Cargos a cuenta");

    // ═══ 10. Ingredients + stock movements (if none exist) ═════════
    const ingCount = await tx.ingredient.count();
    if (ingCount === 0) {
      const ing1 = await tx.ingredient.create({ data: { name: "Queso mozzarella", unit: "kg", currentStock: 5, minStock: 2, cost: 12000 } });
      const ing2 = await tx.ingredient.create({ data: { name: "Harina", unit: "kg", currentStock: 20, minStock: 5, cost: 1800 } });
      const ing3 = await tx.ingredient.create({ data: { name: "Café en grano", unit: "kg", currentStock: 8, minStock: 2, cost: 35000 } });

      await tx.stockMovement.createMany({
        data: [
          { ingredientId: ing1.id, delta: 10, reason: "PURCHASE", unitCost: 12000, notes: "Compra a proveedor" },
          { ingredientId: ing1.id, delta: -5, reason: "ADJUSTMENT", actorName: "Supervisor", notes: "Recuento físico" },
          { ingredientId: ing2.id, delta: 25, reason: "PURCHASE", unitCost: 1800, notes: "Compra a proveedor" },
          { ingredientId: ing3.id, delta: 10, reason: "PURCHASE", unitCost: 35000, notes: "Compra a proveedor" },
        ],
      });
      console.log("  ✅ 3 ingredientes + movimientos de stock");
    } else {
      console.log("  ⏭️  Ingredientes ya existen, salto movimientos de stock");
    }

    // ═══ 11. Staff clocks (entradas/salidas) ════════════════════════
    const now = Date.now();
    await tx.staffClock.createMany({
      data: [
        { staffId: s1.id, type: "IN", timestamp: new Date(now - 1000 * 60 * 60 * 5) },
        { staffId: s1.id, type: "OUT", timestamp: new Date(now - 1000 * 60 * 60 * 1) },
        { staffId: s2.id, type: "IN", timestamp: new Date(now - 1000 * 60 * 60 * 4) },
        { staffId: s3.id, type: "IN", timestamp: new Date(now - 1000 * 60 * 60 * 3) },
        { staffId: gerente.id, type: "IN", timestamp: new Date(now - 1000 * 60 * 60 * 6) },
      ],
    });
    console.log("  ✅ Clocks de personal");
  });

  console.log("✅ [seed-demo] Demo data seeded successfully.");
  await prisma.$disconnect();
}

main().catch(async (e) => {
  console.error("❌ [seed-demo] Error:", e);
  await prisma.$disconnect();
  process.exit(1);
});
