import { NextResponse } from "next/server";
export const dynamic = "force-static";

const HTML = `<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Hangar 5 — Carta Aventura</title><style>
@page{size:letter;margin:0}*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Georgia','Times New Roman',serif;background:#f5f0e8;color:#2d1f14;max-width:8.5in;margin:0 auto;font-size:8pt;line-height:1.4;letter-spacing:.01em;position:relative;overflow-x:hidden}
body::before{content:'';position:fixed;top:0;left:0;right:0;bottom:0;background-image:url('/img/cartas/carta-wanderlust-sketchbook.jpg');background-size:cover;background-position:center;background-attachment:fixed;opacity:.6;z-index:0;pointer-events:none}
body::after{content:'';position:fixed;top:0;left:0;right:0;bottom:0;background:linear-gradient(180deg,rgba(245,240,232,.85) 0%,rgba(245,240,232,.7) 50%,rgba(245,240,232,.9) 100%);z-index:0;pointer-events:none}
.page{position:relative;z-index:1;padding:.4in .35in .35in}
.geo-header{display:flex;align-items:center;gap:16px;margin-bottom:10px;padding-bottom:8px;border-bottom:1.5px solid #2d1f14}
.geo-header .lines{display:flex;flex-direction:column;gap:3px;flex:1}
.geo-header .lines span{display:block;height:.5px;background:#2d1f14}
.geo-header .lines span:nth-child(1){width:100%}.geo-header .lines span:nth-child(2){width:80%}.geo-header .lines span:nth-child(3){width:60%}
.geo-header .title-block{text-align:right;white-space:nowrap}
.geo-header .title-block .brand{font-size:20pt;font-weight:700;letter-spacing:.12em;text-transform:uppercase;line-height:1;color:#1b4235;font-family:'Georgia',serif}
.geo-header .title-block .sub{font-size:6pt;text-transform:uppercase;letter-spacing:.3em;color:#5c3d2e;margin-top:3px;font-family:'Helvetica Neue',sans-serif}
.menu-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px 18px}
.grid-section{break-inside:avoid}.grid-section.full{grid-column:1/-1}.grid-section.span2{grid-column:span 2}
.section-head{font-size:5.5pt;text-transform:uppercase;letter-spacing:.35em;color:#b88364;border-bottom:.5px solid rgba(184,131,100,.4);padding-bottom:3px;margin-bottom:5px;font-family:'Helvetica Neue',sans-serif}
.menu-item{display:flex;justify-content:space-between;align-items:baseline;padding:1.5px 0}
.menu-item .name{font-weight:400;color:#2d1f14}
.menu-item .dots{flex:1;border-bottom:1px dotted rgba(184,131,100,.35);margin:0 6px;height:0;align-self:flex-end;margin-bottom:3px}
.menu-item .price{font-weight:400;color:#5c3d2e;white-space:nowrap;font-family:'Helvetica Neue',sans-serif}
.note{font-size:6pt;color:#8b6f5e;font-style:italic;padding:0 0 2px 0;font-family:'Georgia',serif}
.geo-footer{margin-top:10px;padding-top:5px;border-top:1.5px solid #2d1f14;display:flex;justify-content:space-between;font-size:5.5pt;text-transform:uppercase;letter-spacing:.25em;color:#8b6f5e;font-family:'Helvetica Neue',sans-serif}
</style></head><body>
<div class="page">
<div class="geo-header"><div class="lines"><span></span><span></span><span></span></div><div class="title-block"><div class="brand">Hangar 5</div><div class="sub">Cocina de Montaña &middot; El Peñón, Temascaltepec</div></div></div>
<div class="menu-grid">
<div class="grid-section"><div class="section-head">Cafetería</div><div class="menu-item"><span class="name">Café</span><span class="dots"></span><span class="price">$30</span></div><div class="menu-item"><span class="name">Americano</span><span class="dots"></span><span class="price">$50</span></div><div class="menu-item"><span class="name">Espresso</span><span class="dots"></span><span class="price">$50</span></div><div class="menu-item"><span class="name">Latte</span><span class="dots"></span><span class="price">$60</span></div></div>
<div class="grid-section"><div class="section-head">Sin Alcohol</div><div class="menu-item"><span class="name">Agua de Fruta</span><span class="dots"></span><span class="price">$10</span></div><div class="menu-item"><span class="name">Smoothie Berry</span><span class="dots"></span><span class="price">$60</span></div><div class="menu-item"><span class="name">Smoothie ChocoBanana</span><span class="dots"></span><span class="price">$60</span></div><div class="menu-item"><span class="name">Piña Colada</span><span class="dots"></span><span class="price">$100</span></div><div class="menu-item"><span class="name">Coca Cola</span><span class="dots"></span><span class="price">$30</span></div><div class="note">Light &middot; Zero disponibles</div><div class="menu-item"><span class="name">Agua Mineral</span><span class="dots"></span><span class="price">$30</span></div><div class="menu-item"><span class="name">Jugo Naranja</span><span class="dots"></span><span class="price">$35</span></div><div class="menu-item"><span class="name">Té Infusión</span><span class="dots"></span><span class="price">$30</span></div></div>
<div class="grid-section"><div class="section-head">Con Alcohol</div><div class="menu-item"><span class="name">Copa Vino</span><span class="dots"></span><span class="price">$100</span></div><div class="menu-item"><span class="name">Mezcalina</span><span class="dots"></span><span class="price">$90</span></div><div class="menu-item"><span class="name">Margarita</span><span class="dots"></span><span class="price">$130</span></div><div class="menu-item"><span class="name">Mojito</span><span class="dots"></span><span class="price">$150</span></div><div class="menu-item"><span class="name">Paloma Tequila</span><span class="dots"></span><span class="price">$130</span></div><div class="menu-item"><span class="name">Carajillo</span><span class="dots"></span><span class="price">$150</span></div><div class="menu-item"><span class="name">Cerveza</span><span class="dots"></span><span class="price">$35</span></div><div class="note">Chelada $40 &middot; Michelada $50</div><div class="menu-item"><span class="name">Shot Tequila</span><span class="dots"></span><span class="price">$100</span></div><div class="menu-item"><span class="name">Shot Mezcal</span><span class="dots"></span><span class="price">$100</span></div><div class="menu-item"><span class="name">Whisky</span><span class="dots"></span><span class="price">$100</span></div></div>
<div class="grid-section full"><div class="section-head">Desayunos &middot; Todo el día</div><div style="display:flex;gap:24px"><div style="flex:1"><div class="menu-item"><span class="name">Chilaquiles</span><span class="dots"></span><span class="price">$70</span></div><div class="note">Salsa verde o roja &middot; Con pollo $90</div><div class="menu-item"><span class="name">Huevos a la Mexicana</span><span class="dots"></span><span class="price">$70</span></div><div class="menu-item"><span class="name">Huevos Rancheros</span><span class="dots"></span><span class="price">$70</span></div></div><div style="flex:1"><div class="menu-item"><span class="name">Huevo Champiñones</span><span class="dots"></span><span class="price">$70</span></div><div class="menu-item"><span class="name">Huevos con Jamón</span><span class="dots"></span><span class="price">$80</span></div><div class="menu-item"><span class="name">Fruta de Temporada</span><span class="dots"></span><span class="price">$65</span></div><div class="note">Miel de abeja y chile piquín</div></div></div></div>
<div class="grid-section full"><div class="section-head">Entradas &amp; Ensaladas</div><div style="display:flex;gap:24px"><div style="flex:1"><div class="menu-item"><span class="name">Guacamole</span><span class="dots"></span><span class="price">$110</span></div><div class="menu-item"><span class="name">Aceitunas</span><span class="dots"></span><span class="price">$75</span></div><div class="menu-item"><span class="name">Quesadillas</span><span class="dots"></span><span class="price">$25</span></div><div class="menu-item"><span class="name">Empanadas</span><span class="dots"></span><span class="price">$35</span></div><div class="menu-item"><span class="name">Flautas</span><span class="dots"></span><span class="price">$40</span></div></div><div style="flex:1"><div class="menu-item"><span class="name">Ensalada Caprese</span><span class="dots"></span><span class="price">$130</span></div><div class="note">Mozzarella fresca, albahaca, jitomate</div><div class="menu-item"><span class="name">Ensalada Tropical</span><span class="dots"></span><span class="price">$130</span></div><div class="note">Mango, fresa, aguacate, nuez</div><div class="menu-item"><span class="name">Ensalada Mixta</span><span class="dots"></span><span class="price">$90</span></div></div></div></div>
<div class="grid-section"><div class="section-head">Parrilla</div><div class="menu-item"><span class="name">Hamburguesa Wagyu</span><span class="dots"></span><span class="price">$250</span></div><div class="note">200g carne premium, pan artesanal</div><div class="menu-item"><span class="name">Taco</span><span class="dots"></span><span class="price">$30</span></div><div class="note">Pollo deshebrado, cilantro, salsa</div></div>
<div class="grid-section span2"><div class="section-head">Horno de Leña</div><div style="display:flex;gap:20px"><div style="flex:1"><div class="menu-item"><span class="name">Margarita</span><span class="dots"></span><span class="price">$200</span></div><div class="menu-item"><span class="name">Pepperoni</span><span class="dots"></span><span class="price">$240</span></div><div class="menu-item"><span class="name">Prosciutto</span><span class="dots"></span><span class="price">$240</span></div></div><div style="flex:1"><div class="menu-item"><span class="name">Champiñones</span><span class="dots"></span><span class="price">$220</span></div><div class="menu-item"><span class="name">Tomate Deshidratado</span><span class="dots"></span><span class="price">$240</span></div><div class="menu-item"><span class="name">Vegetariana</span><span class="dots"></span><span class="price">$240</span></div></div></div></div>
<div class="grid-section"><div class="section-head">Postres</div><div class="menu-item"><span class="name">Flan Napolitano</span><span class="dots"></span><span class="price">$40</span></div><div class="menu-item"><span class="name">Panqué Plátano</span><span class="dots"></span><span class="price">$40</span></div><div class="menu-item"><span class="name">Panqué Queso</span><span class="dots"></span><span class="price">$40</span></div><div class="menu-item"><span class="name">Pay de Queso</span><span class="dots"></span><span class="price">$40</span></div><div class="menu-item"><span class="name">Pizza Nutella</span><span class="dots"></span><span class="price">$200</span></div></div>
<div class="grid-section"><div class="section-head">Cafetería Comida</div><div class="menu-item"><span class="name">Panqué del día</span><span class="dots"></span><span class="price">$40</span></div><div class="menu-item"><span class="name">Sándwich</span><span class="dots"></span><span class="price">$70</span></div></div>
</div>
<div class="geo-footer"><span>Hangar 5 &middot; El Peñón, Temascaltepec</span><span>Precios MXN &middot; IVA incluido</span></div>
</div></body></html>`;

export async function GET() {
  return new NextResponse(HTML, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}
