import { NextResponse } from "next/server";
export const dynamic = "force-static";
const HTML = `<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Hangar 5 — Carta Aventura</title><style>
@page{size:letter;margin:0}*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Helvetica Neue','Inter',sans-serif;background:#faf7f5;color:#1b4235;max-width:8.5in;margin:0 auto;font-size:7pt;line-height:1.35;overflow-x:hidden;position:relative}
/* Mountain silhouette background */
.mountains{position:fixed;bottom:0;left:0;right:0;height:200px;opacity:.06;z-index:0;pointer-events:none}
.page{position:relative;z-index:1;padding:.3in .25in}
/* Topographic lines decoration */
.topo{position:absolute;top:.15in;left:.15in;width:100px;height:100px;opacity:.08;z-index:0}
h1{font-size:26pt;font-weight:900;letter-spacing:.12em;text-transform:uppercase;line-height:1;margin-bottom:0}
.sub{font-size:6pt;letter-spacing:.35em;text-transform:uppercase;color:#b88364;margin-bottom:4px}
.tag{font-size:5.5pt;font-style:italic;color:#e07a5f;margin-bottom:14px}
/* Flight lines */
.flight{position:absolute;top:.2in;right:.1in;opacity:.1;z-index:0}
.section{margin-bottom:8px;break-inside:avoid}
.section h2{font-size:5.5pt;letter-spacing:.3em;text-transform:uppercase;color:#e07a5f;border-bottom:1px solid #e07a5f33;padding-bottom:2px;margin-bottom:4px}
.grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px 14px}
.col2{grid-column:span 2}
.full{grid-column:1/-1}
.item{display:flex;justify-content:space-between;align-items:baseline;padding:1px 0}
.item .n{font-weight:500;color:#1b4235}
.item .trail{flex:1;border-bottom:1px dotted #b8836444;margin:0 5px;align-self:flex-end;margin-bottom:3px}
.item .p{color:#b88364;white-space:nowrap;font-weight:500}
.note{font-size:5pt;color:#888;font-style:italic;padding-left:8px}
.bottom{position:absolute;bottom:.15in;right:.15in;opacity:.08;z-index:0}
.footer{margin-top:8px;padding-top:4px;border-top:1px solid #1b423522;font-size:5pt;letter-spacing:.25em;text-transform:uppercase;color:#888;display:flex;justify-content:space-between}
</style></head><body>
<svg class="mountains" viewBox="0 0 800 200"><polygon points="0,200 0,80 80,30 160,90 240,20 320,70 400,10 480,60 560,25 640,75 720,15 800,55 800,200"/><polygon points="0,200 0,120 60,70 140,110 220,50 300,100 380,40 460,90 540,30 620,85 700,25 800,65 800,200" opacity=".5"/></svg>
<svg class="topo" viewBox="0 0 100 100"><path d="M10,50 Q30,20 50,50 T90,50" fill="none" stroke="#1b4235" stroke-width=".5"/><path d="M10,60 Q30,30 50,60 T90,60" fill="none" stroke="#1b4235" stroke-width=".5"/><path d="M10,70 Q30,40 50,70 T90,70" fill="none" stroke="#1b4235" stroke-width=".5"/></svg>
<svg class="flight" width="150" height="80"><path d="M0,40 Q40,5 80,35 T150,15" fill="none" stroke="#e07a5f" stroke-width="1.5" stroke-dasharray="4,3"/><path d="M0,60 Q50,20 100,50 T150,30" fill="none" stroke="#b88364" stroke-width="1"/></svg>
<svg class="bottom" width="120" height="40"><circle cx="20" cy="20" r="18" fill="none" stroke="#1b4235" stroke-width=".5"/><circle cx="20" cy="20" r="8" fill="none" stroke="#1b4235" stroke-width=".5"/><line x1="38" y1="20" x2="120" y2="20" stroke="#1b4235" stroke-width=".5"/></svg>
<div class="page">
<h1>Hangar 5</h1>
<div class="sub">Cocina de Montana</div>
<div class="tag">Penon del Marques &middot; Sabores con altura</div>
<div class="grid">
<div class="section"><h2>Cafeteria</h2><div class="item"><span class="n">Cafe</span><span class="trail"></span><span class="p">30</span></div><div class="item"><span class="n">Cafe Americano</span><span class="trail"></span><span class="p">50</span></div><div class="item"><span class="n">Espresso</span><span class="trail"></span><span class="p">50</span></div><div class="item"><span class="n">Latte</span><span class="trail"></span><span class="p">60</span></div></div>
<div class="section col2"><h2>Sin Alcohol</h2><div style="display:flex;gap:10px"><div style="flex:1"><div class="item"><span class="n">Agua de Fruta</span><span class="trail"></span><span class="p">10</span></div><div class="item"><span class="n">Smoothie Berry</span><span class="trail"></span><span class="p">60</span></div><div class="item"><span class="n">Smoothie ChocoBanana</span><span class="trail"></span><span class="p">60</span></div><div class="item"><span class="n">Pina Colada</span><span class="trail"></span><span class="p">100</span></div><div class="item"><span class="n">Coca Cola</span><span class="trail"></span><span class="p">30</span></div><div class="note">Light &middot; Zero disponibles</div></div><div style="flex:1"><div class="item"><span class="n">Agua Mineral</span><span class="trail"></span><span class="p">30</span></div><div class="item"><span class="n">Agua 1L</span><span class="trail"></span><span class="p">30</span></div><div class="item"><span class="n">Agua 500ml</span><span class="trail"></span><span class="p">15</span></div><div class="item"><span class="n">Jugo Naranja</span><span class="trail"></span><span class="p">35</span></div><div class="item"><span class="n">Suero</span><span class="trail"></span><span class="p">35</span></div><div class="item"><span class="n">Clamato</span><span class="trail"></span><span class="p">40</span></div><div class="item"><span class="n">Te Infusion</span><span class="trail"></span><span class="p">30</span></div></div></div></div>
<div class="section full"><h2>Con Alcohol</h2><div style="display:flex;gap:14px"><div style="flex:1"><div class="item"><span class="n">Copa Vino</span><span class="trail"></span><span class="p">100</span></div><div class="item"><span class="n">Mezcalina</span><span class="trail"></span><span class="p">90</span></div><div class="item"><span class="n">Pina Colada</span><span class="trail"></span><span class="p">150</span></div><div class="item"><span class="n">Margarita</span><span class="trail"></span><span class="p">130</span></div><div class="item"><span class="n">Mojito</span><span class="trail"></span><span class="p">150</span></div><div class="item"><span class="n">Paloma Tequila</span><span class="trail"></span><span class="p">130</span></div><div class="item"><span class="n">Carajillo</span><span class="trail"></span><span class="p">150</span></div></div><div style="flex:1"><div class="item"><span class="n">Cerveza</span><span class="trail"></span><span class="p">35</span></div><div class="note">Chelada 40 &middot; Michelada 50</div><div class="item"><span class="n">Shot Tequila</span><span class="trail"></span><span class="p">100</span></div><div class="item"><span class="n">Shot Mezcal</span><span class="trail"></span><span class="p">100</span></div><div class="item"><span class="n">Whisky</span><span class="trail"></span><span class="p">100</span></div><div class="item"><span class="n">Whisky Soda</span><span class="trail"></span><span class="p">130</span></div><div class="item"><span class="n">Botella Vino</span><span class="trail"></span><span class="p">550</span></div></div></div></div>
<div class="section full"><h2>Desayunos &middot; Todo el dia</h2><div style="display:flex;gap:14px"><div style="flex:1"><div class="item"><span class="n">Chilaquiles</span><span class="trail"></span><span class="p">70</span></div><div class="note">Salsa verde o roja &middot; Con pollo 90</div><div class="item"><span class="n">Huevos a la Mexicana</span><span class="trail"></span><span class="p">70</span></div><div class="item"><span class="n">Huevos Rancheros</span><span class="trail"></span><span class="p">70</span></div></div><div style="flex:1"><div class="item"><span class="n">Huevo Champinones</span><span class="trail"></span><span class="p">70</span></div><div class="item"><span class="n">Huevos con Jamon</span><span class="trail"></span><span class="p">80</span></div><div class="item"><span class="n">Fruta de Temporada</span><span class="trail"></span><span class="p">65</span></div><div class="note">Miel de abeja y chile piquin</div></div></div></div>
<div class="section full"><h2>Entradas &amp; Ensaladas</h2><div style="display:flex;gap:14px"><div style="flex:1"><div class="item"><span class="n">Guacamole</span><span class="trail"></span><span class="p">110</span></div><div class="item"><span class="n">Aceitunas</span><span class="trail"></span><span class="p">75</span></div><div class="item"><span class="n">Quesadillas</span><span class="trail"></span><span class="p">25</span></div><div class="item"><span class="n">Empanadas</span><span class="trail"></span><span class="p">35</span></div><div class="item"><span class="n">Flautas</span><span class="trail"></span><span class="p">40</span></div><div class="item"><span class="n">Verduras</span><span class="trail"></span><span class="p">75</span></div></div><div style="flex:1"><div class="item"><span class="n">Ensalada Caprese</span><span class="trail"></span><span class="p">130</span></div><div class="note">Mozzarella fresca, albahaca</div><div class="item"><span class="n">Ensalada Tropical</span><span class="trail"></span><span class="p">130</span></div><div class="note">Mango, fresa, aguacate, nuez</div><div class="item"><span class="n">Ensalada Mixta</span><span class="trail"></span><span class="p">90</span></div></div></div></div>
<div class="section"><h2>Parrilla</h2><div class="item"><span class="n">Hamburguesa Wagyu</span><span class="trail"></span><span class="p">250</span></div><div class="note">200g carne premium, pan artesanal</div><div class="item"><span class="n">Taco</span><span class="trail"></span><span class="p">30</span></div><div class="note">Pollo deshebrado, cilantro</div></div>
<div class="section col2"><h2>Horno de Lena</h2><div style="display:flex;gap:10px"><div style="flex:1"><div class="item"><span class="n">Margarita</span><span class="trail"></span><span class="p">200</span></div><div class="item"><span class="n">Pepperoni</span><span class="trail"></span><span class="p">240</span></div><div class="item"><span class="n">Prosciutto</span><span class="trail"></span><span class="p">240</span></div></div><div style="flex:1"><div class="item"><span class="n">Champinones</span><span class="trail"></span><span class="p">220</span></div><div class="item"><span class="n">Tomate Deshidratado</span><span class="trail"></span><span class="p">240</span></div><div class="item"><span class="n">Vegetariana</span><span class="trail"></span><span class="p">240</span></div></div></div></div>
<div class="section"><h2>Postres</h2><div class="item"><span class="n">Flan Napolitano</span><span class="trail"></span><span class="p">40</span></div><div class="item"><span class="n">Panque Platano</span><span class="trail"></span><span class="p">40</span></div><div class="item"><span class="n">Panque Queso</span><span class="trail"></span><span class="p">40</span></div><div class="item"><span class="n">Pay de Queso</span><span class="trail"></span><span class="p">40</span></div><div class="item"><span class="n">Pizza Nutella</span><span class="trail"></span><span class="p">200</span></div></div>
<div class="section"><h2>Cafeteria</h2><div class="item"><span class="n">Panque del dia</span><span class="trail"></span><span class="p">40</span></div><div class="item"><span class="n">Sandwich</span><span class="trail"></span><span class="p">70</span></div></div>
</div>
<div class="footer"><span>Hangar 5 &middot; Penon del Marques</span><span>Precios MXN &middot; IVA incluido</span></div>
</div></body></html>`;
export async function GET(){return new NextResponse(HTML,{headers:{"Content-Type":"text/html; charset=utf-8"}})}
